### ISSUE TITLE
Powermock Configuration

### ISSUE THREAD

**Issue by thekingnothing** [powermock/powermock#623]
A user(developer) should has a way to configure some feature which will be added so to PowerMock, such like: 

- [x] make each test class loaded by separate class loader  (#609)
- [x] throw exception on mockStatic if the class wasn't prepared for test (#604)
- [x] throw exception on when(Class c) if class wasn't prepared for test  (#622)
- [x] Global PowerMock ignore (#801)

**Comment by johanhaleby** [comment]
I think one should be a bit careful with too fine grained configuration. This will make the code base more difficult to maintain and eventually the API may become too difficult to use and there will be more support. For example right now I don't think that you should be able to configure if we should "throw exception on mockStatic if the class wasn't prepared for test". I believe that this is a choice that we should make (i.e. also throw exception) since this is probably what the user wants (when would you not want this?)

When it comes to issue 609 I agree. But this is somewhat already possible. You can define `@PrepareForTest` on the method level and then that method is loaded from a different classloader. But It would be nice if you could indicate it at the class level as well since today I don't think that `@PrepareForTest` at the class-level creates a new classloader (for performance reasons).

What do you think?

**Comment by thekingnothing** [comment]
I agree that too fine grained configuration adds complexity to code and this code hardly support. 

My pointed that we need at first implement feature that will give: 

- for developer as user change configuration/behaviour of PowerMock 
- for developer who develops PowerMock easy way to get configuration for current test at each place of code. 

Then we could discuss what will be added into configuration. Also we need take into account such feature as #604, because it could brake test then a user should have a way to switch it off until it test will be fixed or it should disabled by default for first release.

**Comment by johanhaleby** [comment]
Regarding #604, I'm still dubious regarding need for _not_ having an exception to be thrown if the class not prepared for test? If the user want to switch the test of for some reason why not simply used `@Ignore`?
