### ISSUE TITLE
PowerMock 2 Roadmap

### ISSUE THREAD

**Issue by thekingnothing** [powermock/powermock#725]
- [x] Move to a new organisation (https://github.com/powermock) 
- [x] Migrate from Maven to Gradle (#728)
- [x] Improve release process ( #826) 
- [x] Use Mockito Public API instead internal and copy-pasted code (#726)
- [x] JDK 9 support (#783) 
- [x] Removed deprecated code (#839)

**Comment by tuannv0104** [comment]
Dear 

i'd like ask for the issue https://github.com/jacoco/jacoco/issues/51
When do you can process it on this project?
Do you any planing?

**Comment by thekingn0thing** [comment]
Release Candidate has been released. If there is no major bugs found in next month I will release GA version. 
https://github.com/powermock/powermock/releases/tag/powermock-2.0.0-RC.1
