### ISSUE TITLE
Mockito Public API Support Roadmap 

### ISSUE THREAD

**Issue by thekingnothing** [powermock/powermock#726]
Powermock is heavily relying on the internal workings of Mockito. As result hight cost of compatibility  maintenance. We should move to using public SPI. Mockito team is ready to help and provide change in API. 

Main goal: clean code without dirty hacks to get internals of Mockito. 

We need: 

- [x] Identify using of Mockito internals and create a change request for Mockito 
- [x] Replace using internals of Mockito with using public API. 
- [x] Use delegate MockMaker to prevent issue with replacing Mockito MockMaker when PowerMock in class path (see #769, https://github.com/mockito/mockito/pull/1004) 
- [x] Reporter - now internal, need ability to show custom message if mocking is failed for static methods 
- [x] Drop supporting Mockito 1.
 
Current mockito 2 compatibility issues: 

- #720 java.lang.IllegalAccessError: tried to access method org.mockito.internal.util.ObjectMethodsGuru.<init>
- #706 PowerMockito not compatible Mockito2 since their v2.0.55-beta release
- #678 java.lang.NoClassDefFoundError: org/mockito/MockitoAnnotations$Mock 
- #681 Problem when building Mocktio2 with gradle 
- #684 java.lang.NoClassDefFoundError: org/mockito/exceptions/Reporter
- #686 Crash with latest mockito2 
- #700 AbstractMethodError when used with Mockito 2.1.0 
- #774 can't mock final methods with powermock-mockito2 1.7.0.RC4 and mockito2 inline feature enabled

**Comment by zyl0501** [comment]
How to use PowerMockito.mockStatic()?
It return error when I call this method, like [https://github.com/powermock/powermock/issues/720](url).
What is the alternative?

**Comment by thekingnothing** [comment]
@zyl0501, 

Unfortunately, there is no alternative, except use PowerMock with Mockito 1.

**Comment by thekingnothing** [comment]
Experimental supporting Mockito 2.4.0 has been added in PowerMock 1.7.0RC in pull request #740

**Comment by ChristianSchwarz** [comment]
@thekingnothing 
I am contributing to mockito, if you need support or additional APIs for Mockito 2 let me know, i try to help!

**Comment by TheKlint** [comment]
I am trying to use the combo below - but I still get "Exception in thread "main" java.lang.NoClassDefFoundError: org/mockito/exceptions/Reporter"

Is there currently any working combo for PowerMockito.mockStatic()?

    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:2.4.0'
    testCompile "org.powermock:powermock-module-junit4:1.7.0RC2"
    testCompile "org.powermock:powermock-api-mockito:1.7.0RC2"

**Comment by thekingnothing** [comment]
@TheKlint, could you provide full stack trace? How throw exception?

**Comment by HCL-Balaji** [comment]
@thekingnothing I think below exception is mentioned by @TheKlint 
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/mockito/exceptions/Reporter
	at sun.reflect.GeneratedSerializationConstructorAccessor5.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)
	at org.powermock.reflect.internal.WhiteboxImpl.newInstance(WhiteboxImpl.java:260)
	at org.powermock.reflect.Whitebox.newInstance(Whitebox.java:139)
	at org.powermock.api.extension.reporter.AbstractMockingFrameworkReporterFactory.getInstanceForClassLoader(AbstractMockingFrameworkReporterFactory.java:41)
	at org.powermock.api.extension.reporter.AbstractMockingFrameworkReporterFactory.create(AbstractMockingFrameworkReporterFactory.java:35)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.getMockingFrameworkReporter(JUnit4TestSuiteChunkerImpl.java:140)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:119)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.mockito.exceptions.Reporter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:190)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:77)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
```

**Comment by AlekseiMarkov** [comment]
Hi, same problem 
powermock 1.7.0RC2
org.mockito:mockito-core 2.4.0


`  compile group: 'org.powermock', name: 'powermock-api-mockito', version: '1.7.0RC2'
  compile group: 'org.powermock', name: 'powermock-core', version: '1.7.0RC2'
  compile group: 'org.powermock', name: 'powermock-module-junit4', version: '1.7.0RC2'`

`Exception in thread "main" java.lang.NoClassDefFoundError: org/mockito/exceptions/Reporter
	at sun.reflect.GeneratedSerializationConstructorAccessor4.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)
	at org.powermock.reflect.internal.WhiteboxImpl.newInstance(WhiteboxImpl.java:260)
	at org.powermock.reflect.Whitebox.newInstance(Whitebox.java:139)
	at org.powermock.api.extension.reporter.AbstractMockingFrameworkReporterFactory.getInstanceForClassLoader(AbstractMockingFrameworkReporterFactory.java:41)
	at org.powermock.api.extension.reporter.AbstractMockingFrameworkReporterFactory.create(AbstractMockingFrameworkReporterFactory.java:35)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.getMockingFrameworkReporter(JUnit4TestSuiteChunkerImpl.java:140)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:119)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.mockito.exceptions.Reporter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:190)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:77)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more`

**Comment by drayan85** [comment]
I am facing the same issue with below configuration.
**`testCompile 'org.mockito:mockito-core:2.4.0'`
`testCompile 'org.powermock:powermock-module-junit4:1.7.0RC2'`
`testCompile 'org.powermock:powermock-api-mockito:1.7.0RC2'`**

`java.lang.NoClassDefFoundError: org/mockito/exceptions/Reporter`
`at sun.reflect.GeneratedSerializationConstructorAccessor5.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)
	at org.powermock.reflect.internal.WhiteboxImpl.newInstance(WhiteboxImpl.java:260)
	at org.powermock.reflect.Whitebox.newInstance(Whitebox.java:139)
	at org.powermock.api.extension.reporter.AbstractMockingFrameworkReporterFactory.getInstanceForClassLoader(AbstractMockingFrameworkReporterFactory.java:41)
	at org.powermock.api.extension.reporter.AbstractMockingFrameworkReporterFactory.create(AbstractMockingFrameworkReporterFactory.java:35)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.getMockingFrameworkReporter(JUnit4TestSuiteChunkerImpl.java:140)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:119)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)`
`Caused by: java.lang.ClassNotFoundException: org.mockito.exceptions.Reporter`
`at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:190)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:77)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more`

**Comment by thekingnothing** [comment]
@TheKlint @HCL-Balaji @drayan85 @AlekseiMarkov 
> I am trying to use the combo below - but I still get "Exception in thread "main" java.lang.NoClassDefFoundError: org/mockito/exceptions/Reporter"

Please, check dependencies, to use PowerMock with Mockito 2+ it should be not a 
`testCompile "org.powermock:powermock-api-mockito:1.7.0RC2"`

but 

`testCompile "org.powermock:powermock-api-mockito2:1.7.0RC2"`

https://github.com/powermock/powermock/wiki/Mockito-2-(Maven)

**Comment by drayan85** [comment]
@thekingnothing , thanks . with mokito2 working for now.

**Comment by Stianhn** [comment]
@thekingnothing All the "current mockito 2 compatibility issues" listed in the first post are closed, but the wiki still states that Mockito2 support is experimental. What has to be in place before the Mockito2 support is no longer experimental?

**Comment by thekingn0thing** [comment]
The https://github.com/mockito/mockito/issues/1110<https://github.com/mockito/mockito/issues/1110#issuecomment-317418861> should be closed before make supporting Mockito 2 official stable.

We still have some issues, for example cleaning/reset mock could work incorrectly. Things like checking if class ready for static mock was just commented out.

Best regrads,
Arthur Zagretdinov

On 24 Jul 2017, at 11:18, Stian H. Nesbø <notifications@github.com<mailto:notifications@github.com>> wrote:


All the "current mockito 2 compatibility issues" listed in the first post are closed, but the wiki still states that Mockito2 support is experimental. What has to be in place before the Mockito2 support is no longer experimental?

**Comment by thekingn0thing** [comment]
These changes have been released to Maven Central 
https://github.com/powermock/powermock/releases/tag/powermock-2.0.0-RC.1
